### PR TITLE
Fixed exercise bug and welcome/login/register navigation bug

### PR DESCRIPTION
**Pull request by BabaWolo**
Scenario - If an exercise is incorrectly answered it is placed at the end of the section components/exercises. If we reach the last component, the section is completed and handled accordingly.

Bug - If the original last component were correctly answered the section would be completed independent of any previously incorrectly answered questions which now reside after the original last component.

The bug is now fixed and we check the updated list instead of the original section components list.

Additionally, a small navigation bug in the welcome/login/register screens is also fixed.

### CODE REVIEW

**Comment by BabaWolo** [comment]
WIP - Fixing eslint test

**Comment by BabaWolo** [comment]
Test - fixed

**Review by Andersraae — APPROVED** [review]
Not sure about the navigation thing but the fix for out 254 is great, thanks!

**Comment by LucaPurcilly** [comment]
Very nice! Looks good

**Pull request merged**
