### PR TITLE
Cert login save user info

### PR DESCRIPTION
**Pull request by Havkost**
## Description

Save userInfo in local storage on login and remove it on logout.

## Changes

- The following userInfo is now saved in local storage when logging in:
```javascript
{
  id: String,
  firstName: String,
  lastName: String,
  email: String,
}
```
- This userInfo is deleted upon logout.
- Tests have been updated to include these.

## Related Issues

#66 

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## Screenshots (if applicable)

None.

## If mobile/frontend pull request, what version of the backend is it stable, and running on? 

Branch: cert-login-saveUserInfo

Commit id: 6a8d9c00f0189f7f739012325f66ff944c9df4c3

## Notes for Reviewers

Sorry for including ip changes in api files, can't be arsed to remove them now.

### CODE REVIEW

**Review by MaizeHH — APPROVED** [review]
Looks good 😄 only small comment is that there is some inconsistency between using jest's "test" and "it". The test guide uses it but the functionality of these are the exact same so I approve 👍

**Review by Jatewo — APPROVED** [review]
### Very nice 👍

**Comment by Jatewo** [comment]
> Looks good 😄 only small comment is that there is some inconsistency between using jest's "test" and "it". The test guide uses it but the functionality of these are the exact same so I approve 👍

Perhaps this could be changed. I also approve for now, though

**Review by benceisonline — APPROVED** [review]
<3

**Pull request merged**
