### PR TITLE
[APP Courseview] Offline Course view + minor fixes/changes

### PR DESCRIPTION
**Pull request by PrometheusBork**
## Description

This adds a kind of greyify effect to courses that are not downloaded when offline to easily distinguish between available and non-available courses.
It also features some hotfixes.
  
## Changes

- Added conditional layout render for coursescreen based on if a course is downloaded and if you're offline.
- Added functionality so that the download button is disabled when offline.
- Added hotfix for lecture/exercise screen functionality when offline.

## Related Issues

- When uninstalling a course when offline, it can take some time before a course is "greyified".

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.  (on test fails because the test is broken, the function works as intended. The test have been ignored) 
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## If mobile/frontend pull request, what version of the backend is it stable, and running on? 

Branch: dev

Commit id: 65bffdbfb1a9c839a250eeee312e0c35c2d574e1

## Notes for Reviewers

Download a course online first, then close backend and see if it looks like the screenshot when offline

### CODE REVIEW

**Review by Muad3 — APPROVED** [review]
looks fine and runs fine on my emulator also

**Review by Donhusum — APPROVED** [review]
looks okay, we just have to remember to move the asyncstoraef to starageService

**Review by Jatewo — APPROVED** [review]
### Looks good

I can't test if it works, so I'll trust that the tests are sufficient 👍

**Review by JackSMunn — APPROVED** [review]
Looks good to me, did not test locally.

**Pull request merged**
