### PR TITLE
Fixed bug 4.1 and improvement 4.2

### PR DESCRIPTION
**Pull request by MagnusHoese**

### CODE REVIEW

**Comment by magnusklundgren** [comment]
Change base branch from main to dev or group main branch.

**Comment by Laskiri** [comment]
We need to add a Dev and Staging branch.
(1) Base the dev branch from main and make your pull request to it.
(2) Base the staging branch from main. 
Also maybe take a look at the linting errors. 
Changes looks good to me though, but we need to get these other things sorted first 😊👍

**Comment by magnusklundgren** [comment]
Proposed change:
Replace `const namePattern = /^(\p{L}+[- '])*\p{L}+$/u;` and `const emailPattern = /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/;`
With 
if (!patterns.name.test(name)) {
		return `${wordForName} inválido`; // Invalid name
}

The pattern is already defined in a separate file, but then copied into this file. 
A change in the pattern needs to be done in two different places as it is implemented now. The proposed change should eliminate duplication and follow the DRY(Don't Repeat Yourself) principle.

If you want to keep the `namePattern` variable, just put:
const namePattern = patterns.name.

This proposed change is outside the scope for the backlogged issue, but would improve the quality of the codebase.

**Comment by benceisonline** [comment]
i skal merge i dev, ikke main:)

**Comment by MagnusHoese** [comment]
Men brother, dev er bag main

**Comment by benceisonline** [comment]
hvis main har noget som dev ikke har (probs hotfix), så kan i lave en kopi af main og merge den kopi ind i dev inden i merger nye ting ind

**Comment by MagnusHoese** [comment]
Hvis du siger det

**Comment by Lowkee1g** [comment]
Could you please change the base branch for this pull request from ‘dev2’ to ‘Dev’?

**Comment by MBryder** [comment]
Dev branch is up to date change from dev2 to dev

**Review by Andersraae — APPROVED** [review]

**Pull request merged**
