### PR TITLE
Gamified documentation 

### PR DESCRIPTION
**Pull request by amaliedilling**
## Description

added comments for documentation in all gamified files + quick fix of completeCourse screen

### CODE REVIEW

**Review by benceisonline — APPROVED** [review]
LGTM!🦃 🦃 🦃

**Review by MaizeHH — APPROVED** [review]
Looks good! 🦆

**Review by Jatewo — COMMENTED** [review]
Is it possible to make these comments with Doxygen as agreed upon? I know, we're a bit tight on time so I won't gatekeep for this but it shouldn't take long 😄

**Review by TheMOHD3886 — APPROVED** [review]
good stuff fellas 👍

**Pull request merged**
